name: VitNX Builder

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "Build"
  Build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

#     - name: Setup NuGet
#       uses: NuGet/setup-nuget@v1.0.5

#     - name: Restore NuGet packages
#       run: nuget restore source\VitNX.sln

    - name: Build the VitNX
      run: msbuild source\VitNX\VitNX.csproj /p:Configuration=Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: VitNX2.dll
        path: source\VitNX\bin\Release
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: VitNX2.dll
        path: source\VitNX\bin\Release
